apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: final
  labels:
    app: employees
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
  selector:
    app: employees
