apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: final
  labels:
    app: employees
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: employees
