apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: app
  labels:
    app: employees
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30000
  selector:
    app: employees
