apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: final
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: creds-final
      containers:
        - name: app
          image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-final:my_app
          env:
            - name: DBHOST
              value: "db-svc.sqldb.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "pw"
          ports:
          - containerPort: 8081
