apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-dep
          image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-final:my_db
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: final_cred
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-db
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-db
          persistentVolumeClaim:
            claimName: db-pvc  
