apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: creds-final
      containers:
        - name: mysql
          image: http://558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-final:my_db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
          ports:
            - containerPort: 3306
