apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: my_db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
          ports:
            - containerPort: 3306
