apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: final
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: creds-final
      serviceAccountName: clo835
      containers:
        - name: app-dep
          image: 063129952770.dkr.ecr.us-east-1.amazonaws.com/webapp:v1.1
          env:
            - name: DBHOST
              value: "db-svc.final.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DBUSER   
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MYSQL_ROOT_PASSWORD
                  
          envFrom:
            - configMapRef:
                name: app
          ports:
            - containerPort: 81
