apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: final
  name: clo835
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
  apiGroup: ""
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: clo835
